#!/usr/bin/env python3
"""
Generator for the GDG on Campus JIS University — Guidelines & Playbook.
A companion to the Technical Report: same brand system, same toolchain.
Emits dscjisu_guidelines.tex, then compile with:
    latexmk -pdf dscjisu_guidelines.tex   (or)   pdflatex dscjisu_guidelines.tex  x2

This is a living playbook for the next lead. Sections are plain Python
functions returning LaTeX; add or amend a section and rebuild. The GitHub
event-listing / certificate workflow and the org-repo refresh are stubbed in
NEXT_UP() and will be filled in a later revision.
"""
import os

BASE = os.path.dirname(os.path.abspath(__file__))

# ----------------------------------------------------------------------------
# Shared brand preamble — kept in lock-step with the Technical Report so the two
# documents read as one set.
# ----------------------------------------------------------------------------
PREAMBLE = r"""% !TEX program = pdflatex
% GDG on Campus JIS University — Guidelines & Playbook
% GENERATED by build.py — edit data there, not here.
\documentclass[11pt,a4paper]{article}

\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[sfdefault]{roboto}
\usepackage[a4paper,top=2.4cm,bottom=2.2cm,left=2.0cm,right=2.0cm,headsep=14pt]{geometry}
\usepackage{graphicx}
\usepackage{xcolor}
\usepackage{tikz}
\usetikzlibrary{calc,arrows.meta,positioning}
\usepackage[most]{tcolorbox}
\usepackage{fancyhdr}
\usepackage{fontawesome5}
\usepackage{enumitem}
\usepackage{tabularx}
\usepackage{array}
\usepackage{colortbl}
\usepackage{csquotes}
\usepackage[hidelinks]{hyperref}
\usepackage{bookmark}
\hypersetup{pdftitle={GDG on Campus JIS University — Guidelines \& Playbook},
            pdfauthor={Ayushman Bhattacharya},
            pdfsubject={Chapter guidelines and operating playbook},
            bookmarksnumbered=false}

% ---- Google brand palette ----
\definecolor{GBlue}{HTML}{4285F4}
\definecolor{GRed}{HTML}{EA4335}
\definecolor{GYel}{HTML}{FBBC04}
\definecolor{GGrn}{HTML}{34A853}
\definecolor{Ink}{HTML}{202124}
\definecolor{Slate}{HTML}{5F6368}
\definecolor{Mist}{HTML}{F1F3F4}
\definecolor{Line}{HTML}{DADCE0}
\color{Ink}

% ---- running header / footer ----
\pagestyle{fancy}
\fancyhf{}
\renewcommand{\headrulewidth}{0pt}
\renewcommand{\footrulewidth}{0pt}
\fancyfoot[C]{\footnotesize\color{Slate}%
  \textcolor{GBlue}{\rule[-1pt]{7pt}{7pt}}\hspace{2pt}%
  GDG on Campus JIS University \,\textperiodcentered\, Guidelines \& Playbook \,\textperiodcentered\, Dept. of CSE}
\fancyfoot[R]{\footnotesize\color{Slate}\thepage}
\fancyhead[L]{\footnotesize\color{Slate}\leftmark}
\renewcommand{\sectionmark}[1]{\markboth{#1}{}}

\setlength{\parindent}{0pt}
\setlength{\parskip}{5pt}

% four-colour rule used as a divider throughout
\newcommand{\gbar}[1][\linewidth]{%
  \begin{tikzpicture}
    \fill[GBlue] (0,0) rectangle (0.25*#1,0.11);
    \fill[GRed]  (0.25*#1,0) rectangle (0.50*#1,0.11);
    \fill[GYel]  (0.50*#1,0) rectangle (0.75*#1,0.11);
    \fill[GGrn]  (0.75*#1,0) rectangle (#1,0.11);
  \end{tikzpicture}}

% developer-brackets mark (vector), used as a small accent
\newcommand{\devmark}[1]{%
  \begin{tikzpicture}[x=1cm,y=1cm]
    \def\h{#1}
    \fill[GBlue] (0,0) -- (0.34*\h,0.5*\h) -- (0.12*\h,0.5*\h) -- (-0.22*\h,0) -- cycle;
    \fill[GRed]  (0,\h) -- (0.34*\h,0.5*\h) -- (0.12*\h,0.5*\h) -- (-0.22*\h,\h) -- cycle;
    \fill[GGrn]  (0.9*\h,0) -- (0.56*\h,0.5*\h) -- (0.78*\h,0.5*\h) -- (1.12*\h,0) -- cycle;
    \fill[GYel]  (0.9*\h,\h) -- (0.56*\h,0.5*\h) -- (0.78*\h,0.5*\h) -- (1.12*\h,\h) -- cycle;
  \end{tikzpicture}}

% section header: coloured title + four-colour rule
\newcommand{\ghead}[2]{%
  \phantomsection\addcontentsline{toc}{section}{#1}%
  \section*{\color{Ink}#2}\gbar[\linewidth]\\[10pt]}

% a numbered pill used to mark policy / step blocks
\newcommand{\pill}[2]{\tikz[baseline]{\node[fill=#1,text=white,font=\bfseries\small,%
  rounded corners=3pt,inner xsep=7pt,inner ysep=2.5pt]{#2};}}
% dark-text pill — for light fills (e.g. yellow) where white text has poor contrast
\newcommand{\pillk}[2]{\tikz[baseline]{\node[fill=#1,text=Ink,font=\bfseries\small,%
  rounded corners=3pt,inner xsep=7pt,inner ysep=2.5pt]{#2};}}
"""

CYCLE = ["GBlue", "GRed", "GYel", "GGrn"]

# ----------------------------------------------------------------------------
# sections
# ----------------------------------------------------------------------------
def cover():
    return r"""
% ============================== COVER ==============================
\thispagestyle{empty}
\vspace*{-2.55cm}%
\noindent\makebox[\linewidth][c]{\includegraphics[width=\paperwidth]{assets/brand/banner_cover.png}}

\vspace{0.45cm}
\begin{center}
  \includegraphics[width=2.3cm]{assets/brand/profile_dscjisu_native.png}\\[0.26cm]
  {\color{Slate}\large Department of Computer Science \& Engineering}\\[0.10cm]
  {\color{Slate}\normalsize JIS University, Kolkata}\\[0.7cm]

  {\fontsize{37}{41}\selectfont\bfseries\color{Ink} Guidelines \& Playbook}\\[0.26cm]
  {\Large\color{GBlue}\bfseries A Handbook for the Next Organiser}\\[0.34cm]
  {\large\color{Slate} GDG on Campus \textperiodcentered\ JIS University}\\[0.55cm]
  \gbar[9cm]\\[0.75cm]

  \begin{tcolorbox}[enhanced,width=12.4cm,colback=white,colframe=Line,boxrule=0.6pt,
      arc=4pt,left=18pt,right=18pt,top=10pt,bottom=10pt,drop shadow={black!12}]
    {\footnotesize\color{Slate}\textsc{Written by}}\\[2pt]
    {\large\bfseries Ayushman Bhattacharya}\\
    {\small\color{Slate} Organiser, GDG on Campus JIS University (2025–26)
      \;\textperiodcentered\; Roll No.\ 23CS2021016}\\[6pt]
    {\color{Line}\rule{\linewidth}{0.5pt}}\\[5pt]
    {\footnotesize\color{Slate}\textsc{To be upheld by}}\\[2pt]
    {\large\bfseries Every Organiser who follows}\\
    {\small\color{Slate} read it, sign it, improve it, hand it forward}
  \end{tcolorbox}
\end{center}
\clearpage
"""

def about():
    return r"""
% ============================== ABOUT ==============================
\ghead{About this Playbook}{About this Playbook}
This document is the operating manual of \textbf{GDG on Campus JIS University} — the standard every
lead is expected to follow. It sets out how the chapter is run: how the core team is formed and what
each role owns; how the community is expected to conduct itself; the integrity, privacy and terms the
chapter holds to; how an event is cleared, run and documented on campus; how events are managed on
GitHub; and how participation certificates are issued.

Leadership turns over every year, and with it the people, the energy and the ideas. What must
\emph{not} turn over is the standard — the way things are done here, the promises the chapter makes to
its members and partners, and the record it keeps of its own work. This playbook is that constant. It
is the chapter's shared, written agreement with itself, so that a new lead never has to guess the
process or re-learn it the hard way, and so the chapter's way of working survives every handover
intact.

It is deliberately practical. Where there is a process — an approval chain, a document to keep, a
standard to meet — it is written here exactly, not left to memory or to a private chat. Treat it as
binding for the routine, and as a floor, never a ceiling, for everything else you choose to build on
top of it.

\begin{tcolorbox}[enhanced,colback=Mist,colframe=Mist,arc=4pt,left=14pt,right=14pt,top=10pt,bottom=10pt,
    borderline west={3pt}{0pt}{GBlue}]
  {\bfseries\color{Ink}How to use it.}\\[2pt]
  Read it in full before your first event, and return to it whenever a question of process or conduct
  comes up. When this playbook speaks to a situation, it is the answer; when it does not, decide in its
  spirit — honestly, in the community's interest — and then write down what you decided, so the next
  lead inherits an answer rather than the same open question.
\end{tcolorbox}

\begin{tcolorbox}[enhanced,colback=white,colframe=GGrn,boxrule=1pt,arc=4pt,
    left=14pt,right=14pt,top=10pt,bottom=10pt]
  {\bfseries\color{GGrn}\faIcon{arrow-right}~Keep it alive.}\\[2pt]
  A playbook that is never updated becomes folklore. When you learn something the hard way, write it
  down here so the next lead does not. Amend it honestly, in your own voice, and sign the handover so
  the chain of responsibility is never broken.
\end{tcolorbox}
\clearpage
"""

def acknowledgement():
    return r"""
% ============================== ACKNOWLEDGEMENT ==============================
\ghead{Acknowledgement \& Declaration}{Acknowledgement \& Declaration}
{\color{Slate}Signed at the handover of leadership, from the outgoing Organiser to the incoming one.
This page is renewed and re-signed every year.}
\vspace{12pt}

\begin{center}
  {\large\bfseries\color{Ink}Leadership Handover}\qquad
  {\large\color{Slate}Season}\;\;{\large\bfseries\color{Ink}20\rule{0.9cm}{0.4pt}\,--\,20\rule{0.9cm}{0.4pt}}
\end{center}
\vspace{14pt}

\begin{tcolorbox}[enhanced,colback=white,colframe=Line,boxrule=0.8pt,arc=5pt,
    left=18pt,right=18pt,top=16pt,bottom=16pt,borderline west={3.5pt}{0pt}{GBlue}]
  {\bfseries\large\color{Ink}Declaration}\\[6pt]
  I have read and understood the guidelines set out in this playbook — the standards of integrity, the
  Code of Conduct, the privacy and terms of the community, the lines of authority, and the processes
  for forming a team and for running and documenting events. As the incoming Organiser of
  \textbf{GDG on Campus JIS University}, I accept responsibility for upholding them, for the conduct of
  the core team I form, and for the honest record of the work done during my tenure.\\[6pt]
  I accept the chapter as it is handed to me, and I undertake to hand it forward — a little larger, a
  little truer than I found it — to whoever carries it next.
\end{tcolorbox}

\vspace{22pt}

\begin{tcolorbox}[enhanced,colback=Mist,colframe=Mist,arc=5pt,left=18pt,right=18pt,top=14pt,bottom=18pt]
  {\footnotesize\color{Slate}\textsc{Handed over by \;\textperiodcentered\; Outgoing Organiser}}\\[46pt]
  \begin{minipage}[b]{0.56\linewidth}{\color{Line}\rule{\linewidth}{0.6pt}}\\[3pt]\textbf{Name}\end{minipage}\hfill
  \begin{minipage}[b]{0.38\linewidth}{\color{Line}\rule{\linewidth}{0.6pt}}\\[3pt]{\small\color{Slate}Signature \& Date}\end{minipage}\\[12pt]
  {\small\color{Slate}Organiser, GDG on Campus JIS University \;\textperiodcentered\; Season \rule{2.2cm}{0.4pt} \;\textperiodcentered\; Roll No.\ \rule{2.6cm}{0.4pt}}
\end{tcolorbox}

\vspace{16pt}

\begin{tcolorbox}[enhanced,colback=Mist,colframe=Mist,arc=5pt,left=18pt,right=18pt,top=14pt,bottom=18pt]
  {\footnotesize\color{Slate}\textsc{Accepted by \;\textperiodcentered\; Incoming Organiser}}\\[46pt]
  \begin{minipage}[b]{0.56\linewidth}{\color{Line}\rule{\linewidth}{0.6pt}}\\[3pt]\textbf{Name}\end{minipage}\hfill
  \begin{minipage}[b]{0.38\linewidth}{\color{Line}\rule{\linewidth}{0.6pt}}\\[3pt]{\small\color{Slate}Signature \& Date}\end{minipage}\\[12pt]
  {\small\color{Slate}Organiser, GDG on Campus JIS University \;\textperiodcentered\; Season \rule{2.2cm}{0.4pt} \;\textperiodcentered\; Roll No.\ \rule{2.6cm}{0.4pt}}
\end{tcolorbox}

\vspace{16pt}
{\footnotesize\color{Slate}\emph{Countersigned by the Faculty Advisor, Department of Computer Science \& Engineering:}
\;\rule{5.5cm}{0.4pt}}
\clearpage
"""

def core_team():
    roles = [
        ("Mentor Manager", "GBlue",
         "Owns technical direction and quality. Guides members, reviews what the chapter ships, and "
         "keeps the bar high across every domain the chapter runs."),
        ("Outreach", "GRed",
         "Builds the chapter's reach — connecting with other GDG chapters and communities, and "
         "creating the memes and attractive promotion that draw people in to join and work with the "
         "chapter."),
        ("Content", "GYel",
         "Writes the captions and posts across the chapter's social channels — the day-to-day public "
         "voice of the chapter."),
        ("Design", "GGrn",
         "Owns the visual identity — posters, banners, certificates, decks and social creatives — "
         "held consistent with the Google / GDG brand."),
    ]
    def _pill(c, name):
        return (r"\pillk{%s}{%s}" if c == "GYel" else r"\pill{%s}{%s}") % (c, name)
    rows = "".join(
        r"%s & %s \\[8pt]" % (_pill(c, name), mandate)
        for name, c, mandate in roles)
    table = (r"\renewcommand{\arraystretch}{1.25}"
             r"\begin{tabularx}{\linewidth}{@{}>{\raggedright\arraybackslash}p{4.4cm} X@{}}"
             r"\textbf{Standing role} & \textbf{Mandate} \\[3pt]\arrayrulecolor{Line}\hline\rule{0pt}{2.4ex}"
             + rows + r"\end{tabularx}")

    return r"""
% ============================== CORE TEAM ==============================
\ghead{Forming the Core Team}{Forming the Core Team}
The core team is the engine of the chapter. Its size and composition decide the year more than any
single event does. Form it deliberately.

\vspace{4pt}
{\bfseries\color{Ink}Principles}
\begin{itemize}[leftmargin=1.4em,itemsep=4pt,topsep=3pt]
  \item \textbf{Every member has a defined role and a deliverable.} No seats without a mandate.
  \item \textbf{Keep it lean.} Prefer a smaller team where everyone is accountable over a large one
        where responsibility is diffuse.
  \item \textbf{Ownership, not titles.} A role is a set of responsibilities someone answers for, not a
        badge.
  \item \textbf{Review participation through the year.} Roles that go unworked should be reassigned,
        not carried.
\end{itemize}

\vspace{6pt}
{\bfseries\color{Ink}Standing roles} \quad{\footnotesize\color{Slate}— fixed every season; fill these first.}
\par\vspace{6pt}
""" + table + r"""

\vspace{10pt}
{\bfseries\color{Ink}Flexible roles} \quad{\footnotesize\color{Slate}— sized to the year.}\\[2pt]
Beyond the standing roles, keep the remaining seats flexible and open them according to what the year
actually needs — more mentors for a hackathon-heavy calendar, more outreach for a partnership push,
and so on. Add roles when there is work to justify them, and only then.
\clearpage
"""

def _policy(pill_color, num, title, icon, body_tex):
    return (r"""
\begin{tcolorbox}[enhanced,breakable,colback=white,colframe=Line,boxrule=0.6pt,arc=5pt,
    left=14pt,right=14pt,top=12pt,bottom=12pt,borderline west={3.5pt}{0pt}{%s},
    before skip=8pt,after skip=12pt]
  {\pill{%s}{%s}}\;\;{\large\bfseries\color{Ink}\faIcon{%s}~~%s}\\[8pt]
  {\color{Line}\rule{\linewidth}{0.5pt}}\\[7pt]
  %s
\end{tcolorbox}
""" % (pill_color, pill_color, num, icon, title, body_tex))

def policies():
    integrity = _policy(CYCLE[0], "01", "Integrity", "balance-scale", r"""
The chapter runs on trust — of its members, the Department, Google and its partners. We keep that
trust by holding to the following, without exception.
\begin{itemize}[leftmargin=1.4em,itemsep=3pt,topsep=2pt]
  \item \textbf{Report figures as recorded.} Attendance, footfall and outcomes are reported as they
        actually happened. We never inflate numbers or overstate results.
  \item \textbf{Handle resources transparently.} Any funds, sponsorship, swag or credits are accounted
        for and spent on the community — never for private benefit.
  \item \textbf{Act in the chapter's interest.} The lead and the team hold their positions in trust
        for the community; the role, its access and its partners are never used for personal gain.
  \item \textbf{Declare conflicts of interest.} Where a personal, financial or outside interest could
        colour a decision, it is disclosed and the person steps back from that decision.
  \item \textbf{Recruit and assign fairly.} Roles, opportunities and recognition are given on merit and
        commitment — not on favouritism, and openly.
  \item \textbf{Honour commitments.} What is promised to speakers, partners, co-hosts and members is
        delivered; if it cannot be, it is communicated early and honestly.
  \item \textbf{Give credit.} Speakers, partners, volunteers and prior leads are acknowledged for
        their work; we do not take credit for what others did.
  \item \textbf{Represent affiliation truthfully.} We use the Google / GDG name and marks only as
        permitted under Google's community and brand guidelines, and never imply an endorsement,
        partnership or authority the chapter does not have.
  \item \textbf{Protect the chapter's name.} Every dealing — online and in person — is conducted so as
        to leave the chapter's standing stronger, not spent.
\end{itemize}""")

    tos = _policy(CYCLE[1], "02", "Terms of Service — Membership", "file-signature", r"""
These terms govern membership and the running of the chapter.
\begin{itemize}[leftmargin=1.4em,itemsep=3pt,topsep=2pt]
  \item \textbf{Who may join.} The chapter is open to anyone interested. There is no barrier to joining
        beyond wanting to take part and agreeing to the Code of Conduct.
  \item \textbf{Lines of authority.} The highest authority of the chapter is the \textbf{Faculty
        Advisor}, followed by the \textbf{chapter lead} (Organiser). Decisions and escalations follow
        that order.
  \item \textbf{Whose events these are.} Events are organised \textbf{by the chapter, not by the
        Department}. Every event the chapter runs is owned solely by the chapter and its co-hosts, as
        applicable.
  \item \textbf{Operating home.} The chapter operates under the Department of Computer Science \&
        Engineering, JIS University, and within Google's program terms for GDG on Campus.
  \item \textbf{Communication channels.} The main community group is kept \textbf{free of any promotion
        other than the club's own}. A separate, dedicated group is maintained for promotions and event
        cross-posts, so the main group stays clean.
  \item \textbf{Voluntary participation.} Membership and all participation are voluntary and carry no
        payment or guarantee of position.
  \item \textbf{Responsible conduct.} Members act and speak in the chapter's name only with the lead's
        authorisation, and uphold the Code of Conduct at all times.
  \item \textbf{Work \& credit.} Work produced for the chapter may be used by the chapter for its
        events, reports and promotion, with the contributor credited.
\end{itemize}""")

    privacy = _policy(CYCLE[2], "03", "Privacy Policy", "user-shield", r"""
How the chapter handles the personal information of its members and attendees.
\begin{itemize}[leftmargin=1.4em,itemsep=3pt,topsep=2pt]
  \item \textbf{What we collect.} Name, roll number, academic year, email, phone number, social or
        GitHub handles where relevant, event registration and attendance, and event photographs.
  \item \textbf{Why we collect it.} Registration, attendance records, issuing certificates, event
        reporting, and communication with members — nothing beyond running the community.
  \item \textbf{Consent.} By registering for an event or joining a channel, a member consents to their
        data being used for those stated purposes.
  \item \textbf{Where it is stored.} In the chapter's dedicated Google Drive folders, and in the
        events repository for event records, with access limited to the core team members who need it.
  \item \textbf{Who can access it.} Access and admin rights are held only by the lead and the specific
        members whose role requires them, and are handed over cleanly when leadership changes.
  \item \textbf{Sharing.} Shared with Google or an event partner only to the extent needed to run the
        event or issue certificates. Personal data is \textbf{never sold} or used for unrelated
        purposes.
  \item \textbf{Communication.} We contact members only through the channels and address they provide,
        and members may opt out of non-essential messages at any time.
  \item \textbf{Photographs.} Photos taken at events may appear in reports and on chapter channels;
        anyone may ask for their image to be withheld or removed.
  \item \textbf{Retention \& removal.} Records are kept for the chapter's institutional memory. A
        member may request correction or removal of their personal data by writing to the lead.
\end{itemize}""")

    coc = _policy(CYCLE[3], "04", "Code of Conduct", "handshake", r"""
Everyone in the community — members, core team, volunteers, speakers and attendees — is expected to
follow this, at every event, online and offline, and in all chapter channels.
\vspace{2pt}
{\bfseries\color{GGrn}Expected.}
\begin{itemize}[leftmargin=1.4em,itemsep=2pt,topsep=1pt]
  \item Be respectful, inclusive and welcoming, regardless of background, gender, or level of
        experience.
  \item Collaborate in good faith; give and take feedback professionally.
  \item Respect the venue, the Department, speakers, partners and fellow members.
  \item Keep community channels on-topic and civil, and represent the chapter well wherever you carry
        its name.
  \item Follow the lead's direction on chapter matters, and honour the commitments you take on.
\end{itemize}
{\bfseries\color{GRed}Not tolerated.}
\begin{itemize}[leftmargin=1.4em,itemsep=2pt,topsep=1pt]
  \item Harassment, discrimination, or intimidation in any form.
  \item Sharing others' private information; plagiarism or passing off others' work as your own.
  \item Disruptive, dishonest or unsafe behaviour at events or online.
  \item Spamming or posting outside promotion in the main community group (see the Terms), or misusing
        the chapter's name.
\end{itemize}
{\bfseries\color{Ink}Membership \& removal.}\;
Core members and other members may be asked to step down, or be removed from the community, for
violating this Code — at the lead's supervision, and in consultation with the Faculty Advisor where
the matter is serious.
\vspace{3pt}\\
{\bfseries\color{Ink}Community channels \& admin rights.}\;
Admin rights of the main WhatsApp group are held by the \textbf{current lead}, \textbf{one or two
trusted members}, and — as an option — \textbf{any of the former organisers}. Admin is handed over as
leadership changes, and the main group is kept free of outside promotion.
\vspace{3pt}\\
{\bfseries\color{Ink}Reporting \& enforcement.}\;
Concerns should be reported to the lead or the Faculty Advisor and are handled confidentially.
Breaches are met with a graduated response — a warning first, and removal from the team or community
where warranted.""")

    return (r"""
% ============================== POLICIES ==============================
\ghead{Integrity, Terms, Privacy \& Conduct}{Integrity, Terms, Privacy \& Conduct}
These four standards are binding on the lead and every member. They are written plainly so there is no
ambiguity about what the chapter expects.
\vspace{6pt}
""" + integrity + tos + privacy + coc + r"\clearpage")

def _flowstep(color, tag, title, lines):
    body = r"\\[3pt]".join(lines)
    return (r"""\begin{tcolorbox}[enhanced,colback=white,colframe=%s,boxrule=1pt,arc=5pt,
    left=14pt,right=14pt,top=9pt,bottom=9pt,width=\linewidth]
  {\pill{%s}{%s}}\;\;{\bfseries\color{Ink}%s}\\[5pt]
  {\small\color{Slate}%s}
\end{tcolorbox}""" % (color, color, tag, title, body))

def _flowarrow(label=""):
    lab = (r"\;{\footnotesize\color{Slate}\itshape %s}" % label) if label else ""
    return (r"\begin{center}{\color{Slate}\Large\faIcon{long-arrow-alt-down}}%s\end{center}" % lab)

def event_flow():
    onsite = "\n".join([
        _flowstep("GBlue", "1", "Email the Faculty Advisor",
                  ["Sent by the student. Seek approval to hold the event —",
                   "share the plan, date, format and partner (if any)."]),
        _flowarrow("on Faculty Advisor approval"),
        _flowstep("GRed", "2", "Email the Department Coordinator",
                  [r"\textbf{cc:} HOI (Registrar) \;\textperiodcentered\; HOD",
                   "Sent by the student, forwarding the approved plan."]),
        _flowarrow("only if audio equipment is needed"),
        _flowstep("GYel", "3", "Request microphone / speaker access",
                  [r"Email \textbf{HOI} and \textbf{Dr.\ Devlina Pal}.",
                   r"\textbf{cc:} Faculty Advisor."]),
    ])

    return r"""
% ============================== EVENT FLOW ==============================
\ghead{Running an Event — Approval Flow}{Running an Event — Approval Flow}
This is the communication chain for clearing an event on campus. It applies to \textbf{on-site events},
whether they are GDG's own or run with a community partner.
\vspace{8pt}

{\bfseries\color{Ink}\faIcon{map-marker-alt}~~On-site event}
\vspace{8pt}

""" + onsite + r"""

\vspace{12pt}
\begin{tcolorbox}[enhanced,colback=white,colframe=GGrn,boxrule=1pt,arc=5pt,
    left=14pt,right=14pt,top=10pt,bottom=10pt]
  {\bfseries\color{GGrn}\faIcon{wifi}~~Online event.}\\[2pt]
  For an online event, the approval chain is not needed — but the event must still be put on record.
  \textbf{Email the Faculty Advisor only}, with the plan and date, so the chapter keeps a documented
  trail of everything it runs.
\end{tcolorbox}

\vspace{4pt}
{\footnotesize\color{Slate}\emph{Steps 1–2 are the student's responsibility. Keep every approval
email — it is part of the event's record (see the next section).}}
\clearpage
"""

def email_and_docs():
    footer = (r"""\begin{tcolorbox}[enhanced,colback=Mist,colframe=Line,boxrule=0.6pt,arc=4pt,
    left=14pt,right=14pt,top=10pt,bottom=10pt]
  {\footnotesize\color{Slate}\textsc{Sample signature — every official email carries this}}\\[6pt]
  {\color{Line}\rule{\linewidth}{0.5pt}}\\[6pt]
  \begin{minipage}[c]{0.16\linewidth}\includegraphics[width=\linewidth]{assets/brand/gdg_jisu_logo.jpg}\end{minipage}\hfill
  \begin{minipage}[c]{0.80\linewidth}
    {\bfseries\color{Ink}Ayushman Bhattacharya}\\
    {\small\color{Slate}Organiser \;\textperiodcentered\; GDG on Campus JIS University\\
    Department of Computer Science \& Engineering, JIS University\\
    \faIcon{phone-alt}~+91\,\rule{2.2cm}{0.4pt} \quad\faIcon{envelope}~\rule{3.6cm}{0.4pt}}
  \end{minipage}
\end{tcolorbox}""")

    return r"""
% ============================== EMAIL & DOCS ==============================
\ghead{Email Standards \& Event Records}{Email Standards \& Event Records}

{\bfseries\color{Ink}\faIcon{envelope-open-text}~~Email footer}\\[2pt]
Every official email sent on the chapter's behalf must carry a consistent footer, so the community is
recognisable and reachable. The footer must include the \textbf{lead's name and role}, the
\textbf{lead's phone number}, and the \textbf{GDG JIS University stamp / logo}.
\vspace{8pt}

""" + footer + r"""

\vspace{14pt}
{\bfseries\color{Ink}\faIcon{folder-open}~~Event records — Google Drive}\\[2pt]
For \textbf{every event, online or offline}, upload the following to the chapter's dedicated Google
Drive folder (one folder per event, named consistently). These three documents are mandatory and are
what make the Technical Report possible.
\vspace{6pt}

\renewcommand{\arraystretch}{1.35}
\begin{tabularx}{\linewidth}{@{}p{0.5cm} >{\raggedright\arraybackslash}p{3.8cm} X@{}}
\pill{GBlue}{1} & \textbf{MoU} & The Memorandum of Understanding for the event / partnership. \\
\pill{GRed}{2} & \textbf{Attendance sheet} & The recorded attendance for the event. \\
\pill{GYel}{3} & \textbf{Event report} & A written report of the event \emph{with images}. \\
\end{tabularx}

\vspace{10pt}
\begin{tcolorbox}[enhanced,colback=Mist,colframe=Mist,arc=4pt,left=14pt,right=14pt,top=9pt,bottom=9pt,
    borderline west={3pt}{0pt}{GBlue}]
  {\footnotesize\color{Slate}Keep the Drive tidy and current. The record you keep today is the
  institutional memory the next lead inherits — and the raw material of every future report.}
\end{tcolorbox}
\clearpage
"""

def github_events():
    tree = r"""\begin{tcolorbox}[enhanced,colback=Mist,colframe=Line,boxrule=0.6pt,arc=4pt,
    left=14pt,right=14pt,top=10pt,bottom=10pt]
{\footnotesize\ttfamily\color{Ink}%
dscjisu/events/\\
\hspace*{1em}.github/\\
\hspace*{2.2em}ISSUE\_TEMPLATE/event.yml \hfill {\rmfamily\itshape\color{Slate}the event schema}\\
\hspace*{2.2em}workflows/update-readme.yml \hfill {\rmfamily\itshape\color{Slate}rebuilds the listing on approval}\\
\hspace*{1em}events/NN-slug/\\
\hspace*{2.2em}event.md \hfill {\rmfamily\itshape\color{Slate}canonical record, from the issue}\\
\hspace*{2.2em}mou.md \hfill {\rmfamily\itshape\color{Slate}drafted MoU, committed ready}\\
\hspace*{2.2em}graphics/ \hfill {\rmfamily\itshape\color{Slate}event banner \& thumbnail}\\
\hspace*{1em}assets/brand/ \hfill {\rmfamily\itshape\color{Slate}GDG brand kit (provided separately)}\\
\hspace*{1em}scripts/generate.py \hfill {\rmfamily\itshape\color{Slate}Pillow — MoU \& certificates}\\
\hspace*{1em}README.md \hfill {\rmfamily\itshape\color{Slate}live public listing (auto-updated)}%
}
\end{tcolorbox}"""

    strip = r"""\noindent\resizebox{\linewidth}{!}{%
\begin{tikzpicture}[x=1cm,y=1cm,
    stg/.style={rounded corners=4pt,inner xsep=8pt,inner ysep=5pt,font=\bfseries,
                text=white,minimum height=0.72cm}]
  \node[stg,fill=Slate] (a) {need-info};
  \node[stg,fill=GBlue,right=11pt of a] (b) {scheduled};
  \node[stg,fill=GGrn,right=11pt of b] (c) {approved};
  \node[stg,fill=GYel,text=Ink,right=11pt of c] (d) {graphics};
  \node[stg,fill=GRed,right=11pt of d] (e) {MoU};
  \node[stg,fill=GBlue,right=11pt of e] (f) {listed};
  \node[stg,fill=GGrn,right=11pt of f] (g) {completed};
  \foreach \s/\t in {a/b,b/c,c/d,d/e,e/f,f/g}
    \draw[-{Latex[length=6pt]},Slate,line width=1pt] (\s.east) -- (\t.west);
\end{tikzpicture}}"""

    stages = [
        ("Slate", "need-info",
         "Draft opened from the template. Required fields are still missing; the owner completes them."),
        ("GBlue", "scheduled",
         "Dated, with full details. Awaiting the on-campus approval flow (see \\emph{Approval Flow})."),
        ("GGrn", "approved",
         "Cleared through the approval flow. The README listing updates automatically."),
        ("GYel", "graphics-ready",
         "Banner and thumbnail made by the Design team and posted on the issue with the GDG event link."),
        ("GRed", "mou-ready",
         "The MoU is drafted and committed in the event repository, ready to sign."),
        ("GBlue", "listed",
         "Registration form and dashboard link set; the event is enlisted on the GDG dashboard."),
        ("GGrn", "completed",
         "Held and archived — records to Drive (see \\emph{Event Records}); the event repo locked, "
         "archived and shared on socials."),
    ]
    def _pill(c, l):
        return (r"\pillk{%s}{%s}" if c == "GYel" else r"\pill{%s}{%s}") % (c, l)
    lrows = "".join(r"%s & %s \\[7pt]" % (_pill(c, l), m) for c, l, m in stages)
    lctable = (r"\renewcommand{\arraystretch}{1.2}"
               r"\begin{tabularx}{\linewidth}{@{}>{\raggedright\arraybackslash}p{3.4cm} X@{}}"
               r"\textbf{Stage \small\color{Slate}(issue label)} & \textbf{Meaning} \\[3pt]"
               r"\arrayrulecolor{Line}\hline\rule{0pt}{2.8ex}" + lrows + r"\end{tabularx}")

    fields = [
        ("Title \\& type", "Event name and kind — workshop, hackathon, meetup, info session, study jam."),
        ("Mode", "On-site or online."),
        ("Date \\& timings", "Scheduled date and start / end time."),
        ("Room / venue", "Room number for on-site; platform for online."),
        ("Description", "A short abstract of the event."),
        ("Expected count", "Anticipated number of participants."),
        ("Speaker(s)", "Names, and whether a speaker image is available to attach."),
        ("Partners", "Community or industry collaborators, if any."),
        ("MoU needed?", "Whether a Memorandum of Understanding is required."),
        ("Registration link", "The Google Form for sign-ups."),
        ("Dashboard link", "The GDG dashboard listing or external event URL."),
        ("Owner", "The core member responsible for the event."),
    ]
    frows = "".join(r"\textbf{%s} & %s \\[4pt]" % (f, n) for f, n in fields)
    schema = (r"\renewcommand{\arraystretch}{1.15}"
              r"\begin{tabularx}{\linewidth}{@{}>{\raggedright\arraybackslash}p{3.7cm} X@{}}"
              r"\textbf{Field} & \textbf{Captured value} \\[3pt]"
              r"\arrayrulecolor{Line}\hline\rule{0pt}{2.4ex}" + frows + r"\end{tabularx}")

    return r"""
% ============================== GITHUB EVENTS ==============================
\ghead{Managing Events on GitHub}{Managing Events on GitHub}
Event coordination lives in one repository — \texttt{dscjisu/events} — the single source of truth for
the whole lifecycle. The model is GitHub's own \emph{Open Source Friday}: an event is an issue, its
stage is a label, and an approved event publishes itself to a public listing. Nothing about an event
lives in someone's head or a private chat. Alongside it, \textbf{every event also gets its own
repository} for the material it produces — slides, code and resources — so nothing worth keeping is
lost.
\vspace{8pt}

""" + tree + r"""

\vspace{12pt}
{\bfseries\color{Ink}The event lifecycle}\quad{\footnotesize\color{Slate}— each event moves through these labelled stages.}
\par\vspace{10pt}
""" + strip + r"""
\vspace{12pt}
""" + lctable + r"""
\clearpage

{\bfseries\color{Ink}Each event has its own repository}\\[2pt]
Beyond the coordination hub, every event gets a dedicated repository holding the material it produces
— the slides / PPT, any code or demos, and the resources meant to be shared. The drafted MoU and the
event graphics live here too, so an event's whole footprint sits in one place.

\vspace{4pt}
\begin{tcolorbox}[enhanced,colback=Mist,colframe=Mist,arc=4pt,left=14pt,right=14pt,top=9pt,bottom=9pt,
    borderline west={3pt}{0pt}{GGrn}]
  {\bfseries\color{Ink}\faIcon{archive}~~When it's done, lock it and share it.}\\[2pt]
  {\small\color{Slate}Once an event repository is locked and set — nothing more to add — it is
  \textbf{archived} (made read-only) and \textbf{shared on the chapter's social profile}, so the work
  stays public and credited even after it goes quiet.}
\end{tcolorbox}

\vspace{14pt}
{\bfseries\color{Ink}The event issue — what it captures}\quad{\footnotesize\color{Slate}— a proposed schema; the lead finalises the fields.}
\par\vspace{8pt}
""" + schema + r"""
\clearpage

{\bfseries\color{Ink}What GitHub manages for us}
\begin{itemize}[leftmargin=1.4em,itemsep=4pt,topsep=3pt]
  \item \textbf{Issues} — one per event, the single canonical record.
  \item \textbf{Issue forms} — structured intake matching the schema, so nothing is missed.
  \item \textbf{Labels} — the lifecycle stage of each event.
  \item \textbf{Project board} — a kanban of every event across the stages; the \emph{Open Source
        Friday} view the core team works from.
  \item \textbf{Assignee} — the core member who owns the event.
  \item \textbf{Actions} — regenerate the README on approval and automate label transitions.
  \item \textbf{Committed artifacts} — the MoU (ready to sign), the event graphics and
        \texttt{event.md}, all version-controlled.
  \item \textbf{README} — the public, always-current listing the dashboard can read from.
\end{itemize}

\vspace{8pt}
\begin{tcolorbox}[enhanced,colback=white,colframe=GGrn,boxrule=1pt,arc=4pt,
    left=14pt,right=14pt,top=11pt,bottom=11pt]
  {\bfseries\color{GGrn}\faIcon{clipboard-check}~~Definition of done — before an event is set out.}\\[6pt]
  {\color{Ink}\faIcon{check-square}~Approved on campus \quad
  \faIcon{check-square}~MoU committed \quad
  \faIcon{check-square}~Graphics linked \quad
  \faIcon{check-square}~Registration form set \quad
  \faIcon{check-square}~Dashboard link set}\\[6pt]
  {\small\color{Slate}Only when all five hold does the event move to \pill{GBlue}{listed} and get
  enlisted on the dashboard.}
\end{tcolorbox}
\clearpage
"""

def graphics_standard():
    assets = (r"\renewcommand{\arraystretch}{1.3}"
              r"\begin{tabularx}{\linewidth}{@{}>{\raggedright\arraybackslash}p{3.2cm} "
              r">{\raggedright\arraybackslash}p{3.4cm} X@{}}"
              r"\textbf{Asset} & \textbf{Size} & \textbf{Use} \\[3pt]"
              r"\arrayrulecolor{Line}\hline\rule{0pt}{2.6ex}"
              r"\pill{GBlue}{Banner} & \textbf{2560 $\times$ 650}\,px & Event header on the dashboard and repository. \\[6pt]"
              r"\pillk{GYel}{Thumbnail} & \textbf{1:1} (square) & Social card and event listing. \\[6pt]"
              r"\end{tabularx}")
    return r"""
% ============================== GRAPHICS ==============================
\ghead{Event Graphics — the Standard}{Event Graphics — the Standard}
Event graphics are owned by the \textbf{Design team}, who make each event's poster in whatever style
suits it — held consistent with the GDG brand. The \emph{style} is free; the \emph{deliverables and
their sizes} are fixed, so every asset drops cleanly into the issue, the dashboard and socials.
\vspace{6pt}

""" + assets + r"""

\vspace{10pt}
{\bfseries\color{Ink}When the graphics are ready}
\begin{itemize}[leftmargin=1.4em,itemsep=4pt,topsep=3pt]
  \item Post the \textbf{thumbnail} and the \textbf{banner} as a comment on the event issue.
  \item Add the \textbf{GDG event link} in the same comment.
  \item Move the event to \pillk{GYel}{graphics-ready}.
\end{itemize}

\begin{tcolorbox}[enhanced,colback=Mist,colframe=Mist,arc=4pt,left=14pt,right=14pt,top=9pt,bottom=9pt,
    borderline west={3pt}{0pt}{GYel}]
  {\footnotesize\color{Slate}Freedom in the look, discipline in the format. Keeping the two sizes fixed
  means a poster made for one event fits every surface it needs to — no re-cropping, no surprises on
  the dashboard.}
\end{tcolorbox}
\clearpage
"""

def mou_standard():
    parts = [
        ("Parties", "GDG on Campus JIS University and the co-host / partner, each named in full."),
        ("Event", "Title, date, and venue or mode."),
        ("Purpose", "What the collaboration is for, in a line or two."),
        ("Responsibilities", "What each party will do — venue, speakers, promotion, logistics."),
        ("Contributions", "Resources each side brings — space, tooling, swag, funds (if any)."),
        ("Branding \\& credit", "How each party is named and credited, and the terms of brand use."),
        ("Data \\& privacy", "How attendee data is handled — per the chapter's Privacy Policy."),
        ("Term", "The dates over which the MoU is valid."),
        ("Points of contact", "One named contact for each party."),
        ("Signatures", "Chapter lead, Faculty Advisor, and the partner's representative."),
    ]
    rows = "".join(r"\textbf{%s} & %s \\[4pt]" % (f, n) for f, n in parts)
    table = (r"\renewcommand{\arraystretch}{1.2}"
             r"\begin{tabularx}{\linewidth}{@{}>{\raggedright\arraybackslash}p{3.7cm} X@{}}"
             r"\textbf{Section} & \textbf{Contents} \\[3pt]"
             r"\arrayrulecolor{Line}\hline\rule{0pt}{2.4ex}" + rows + r"\end{tabularx}")
    return r"""
% ============================== MOU ==============================
\ghead{The MoU — Standard Format}{The MoU — Standard Format}
Every event that involves a co-host or partner carries a \textbf{Memorandum of Understanding}. Its
format is fixed — the same sections every time — so nothing is negotiated from a blank page and
nothing important is left out.
\vspace{6pt}

""" + table + r"""

\vspace{10pt}
\begin{tcolorbox}[enhanced,colback=Mist,colframe=Mist,arc=4pt,left=14pt,right=14pt,top=9pt,bottom=9pt,
    borderline west={3pt}{0pt}{GRed}]
  {\bfseries\color{Ink}\faIcon{file-code}~~Defined here, and in the script.}\\[2pt]
  {\small\color{Slate}These same sections are encoded in the GitHub script (\texttt{scripts/generate.py}),
  which drafts \texttt{mou.md} for each event from the issue — so every MoU follows this format
  automatically and lands in the event repository ready to sign.}
\end{tcolorbox}
\clearpage
"""

def certificates():
    return r"""
% ============================== CERTIFICATES ==============================
\ghead{Registration \& Participation Certificates}{Registration \& Participation Certificates}
Every event has a \textbf{Google Form} prepared before it opens. It captures sign-ups and is the basis
of the attendance record.

\vspace{4pt}
\begin{tcolorbox}[enhanced,colback=white,colframe=GGrn,boxrule=1pt,arc=4pt,
    left=14pt,right=14pt,top=11pt,bottom=11pt]
  {\bfseries\color{GGrn}\faIcon{certificate}~~Eligibility.}\\[2pt]
  A participant who fills the event's Google Form becomes \textbf{eligible for the participation
  certificate}. The form is the single gate between attending and being certified.
\end{tcolorbox}

\vspace{10pt}
{\bfseries\color{Ink}How the certificate is made and sent}\quad{\footnotesize\color{Slate}— the same Pillow discipline as the event graphics.}
\par\vspace{8pt}
""" + certificate_flow() + r"""

\vspace{10pt}
\begin{tcolorbox}[enhanced,colback=Mist,colframe=Mist,arc=4pt,left=14pt,right=14pt,top=9pt,bottom=9pt,
    borderline west={3pt}{0pt}{GBlue}]
  {\footnotesize\color{Slate}The template and both signatures are fixed; only the participant's details
  change. That is what makes issuing hundreds of certificates a single scripted run rather than manual
  work — and keeps every certificate identical but for the name on it.}
\end{tcolorbox}
\clearpage
"""

def certificate_flow():
    steps = "\n".join([
        _flowstep("GBlue", "1", "Collect the eligible list",
                  ["The event's Google Form responses are the eligible participants —",
                   "each row is one certificate to issue."]),
        _flowarrow(""),
        _flowstep("GRed", "2", "Fill GDG's pre-defined template",
                  [r"A \textbf{Pillow} script writes onto GDG's fixed certificate template,",
                   "filling the blanks — participant name, event and date — one per person."]),
        _flowarrow(""),
        _flowstep("GYel", "3", "Signatures at the foot",
                  [r"The template carries, at the bottom, the signatures of the",
                   r"\textbf{current lead} (Organiser) and the \textbf{Faculty Advisor}."]),
        _flowarrow(""),
        _flowstep("GGrn", "4", "Email each participant",
                  ["Each eligible participant is emailed their generated certificate,",
                   "using the chapter's standard email footer."]),
    ])
    return steps

def org_repos():
    return r"""
% ============================== ORG REPOS ==============================
\ghead{Refreshing the Organisation Repositories}{Refreshing the Organisation Repositories}
The \texttt{dscjisu} GitHub organisation carries several years of history. Keeping it tidy is part of
the lead's stewardship — a newcomer landing on the org should immediately see what is active, what
each repository is, and where the current work lives. This is done in phases.
\vspace{6pt}

\renewcommand{\arraystretch}{1.3}
\begin{tabularx}{\linewidth}{@{}p{0.5cm} >{\raggedright\arraybackslash}p{3.8cm} X@{}}
\pill{GBlue}{1} & \textbf{Archive the old} &
  Repositories that are no longer active are \textbf{archived} — made read-only. Nothing is deleted;
  history is preserved, but the retired work is clearly set apart from the live surface. \\
\pill{GRed}{2} & \textbf{Describe the rest} &
  Every kept repository is given a \textbf{clear description} (and topics) so anyone browsing the org
  understands what each one is, without opening it. \\
\pill{GYel}{3} & \textbf{Split for maintenance} &
  Later, the consolidated event folder is \textbf{divided into its respective repositories}, each one
  owned and maintained on its own — the endpoint of the GitHub-based event workflow. \\
\end{tabularx}

\vspace{10pt}
\begin{tcolorbox}[enhanced,colback=white,colframe=GGrn,boxrule=1pt,arc=4pt,left=14pt,right=14pt,top=10pt,bottom=10pt]
  {\bfseries\color{GGrn}\faIcon{robot}~~Automated housekeeping.}\\[2pt]
  {\small\color{Ink}A scheduled workflow in the org's \texttt{.github} repository orchestrates the
  whole organisation. On a timer, it inventories every repository and \textbf{archives those with no
  maintenance for a set period} — leaving a short \textbf{exceptions list} (the profile repos, the
  events hub, and anything explicitly pinned as active) untouched. Housekeeping runs on a schedule,
  not on someone remembering to do it.}
\end{tcolorbox}

\vspace{8pt}
\begin{tcolorbox}[enhanced,colback=Mist,colframe=Mist,arc=4pt,left=14pt,right=14pt,top=9pt,bottom=9pt,
    borderline west={3pt}{0pt}{GBlue}]
  {\bfseries\color{Ink}\faIcon{terminal}~~And scriptable by hand.}\\[2pt]
  {\small\color{Slate}For a one-off pass, the same actions run through the \texttt{gh} CLI —
  \texttt{gh repo archive}, \texttt{gh repo edit -{}-description}, \texttt{gh repo edit -{}-add-topic}
  — so a lead can bring the org up to date in a single sweep whenever needed.}
\end{tcolorbox}
\clearpage
"""

def closing():
    return r"""
% ============================== CLOSING ==============================
\phantomsection\addcontentsline{toc}{section}{A Note to the Next Lead}
\section*{\color{Ink}A Note to the Next Lead}
\gbar[\linewidth]\\[12pt]

You inherit a chapter, a community, and this playbook. Follow it where it is settled, improve it where
it is not, and never let the standards slip below the floor it sets. When your time is done, sign the
handover honestly and pass it on — a little larger, a little truer than you found it.

\vspace{4pt}
\textbf{The community comes first — before any event, any number, any credit, and before your own
convenience.} Everything else in this playbook is downstream of that one idea. To lead is to take up
the work, not to be seen doing it: to carry the load when it is heavy, to be patient when things are
slow, and to be steady enough not to lose your cool when they go wrong. Your first duty is to the
people — to protect the members, make room for them, and make sure no one is used or left behind.

A good lead sees trouble before it arrives. Learn to read the points of failure — the unowned task,
the overloaded volunteer, the unclear agreement, the quiet resentment — and defuse them early. Avoid
conflict where you can; where it cannot be avoided, face it directly, fairly, and in the open, and
take the right action even when it is the harder one. The chapter's calm is your responsibility, and
it is built one steady decision at a time.

\begin{tcolorbox}[enhanced,colback=Mist,colframe=Mist,arc=5pt,left=16pt,right=16pt,top=12pt,bottom=12pt,
    borderline west={3pt}{0pt}{GBlue}]
  {\small\color{Ink}Be patient. Be fair. Protect your people. Keep your word, keep your calm, and keep
  the community first. Do that, and everything this playbook asks of you will follow naturally.}
\end{tcolorbox}

\vfill
\begin{center}
  \devmark{0.9}\\[8pt]
  {\footnotesize\color{Slate} GDG on Campus JIS University \,\textperiodcentered\, Department of Computer Science \& Engineering}\\
  {\footnotesize\color{Slate} This is a living document — keep it alive.}
\end{center}
"""

def contents():
    return r"""
\phantomsection\addcontentsline{toc}{section}{Contents}
\section*{\color{Ink}Contents}
\gbar[\linewidth]\\[8pt]
\begingroup
\hypersetup{linkcolor=Ink}
\renewcommand{\contentsname}{}
\vspace{-3.4em}
\tableofcontents
\endgroup
\clearpage
"""

def build():
    out = [PREAMBLE, r"\begin{document}",
           cover(), about(),
           acknowledgement(), core_team(), policies(),
           event_flow(), email_and_docs(),
           github_events(), graphics_standard(), mou_standard(), certificates(),
           org_repos(), closing(),
           r"\end{document}"]
    return "\n".join(out)

if __name__ == "__main__":
    with open(os.path.join(BASE, "dscjisu_guidelines.tex"), "w") as f:
        f.write(build())
    print("wrote dscjisu_guidelines.tex")
